[package]
name = "rpass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
json = "0.12.4"
ring = "0.17.5"
rusqlite = "0.30.0"
rustls = "0.21.9"
serde = "1.0.193"
